### ISSUE TITLE
Plugin is not compatible with Gradle 4.2

### ISSUE THREAD

**Issue by ronocod** [novoda/bintray-release#138]
I get an error when trying to use Gradle 4.2 or 4.2.1 with the plugin:
```
Caused by: groovy.lang.MissingPropertyException: No such property: FOR_RUNTIME for class: org.gradle.api.attributes.Usage
        at com.novoda.gradle.release.AndroidLibrary$RuntimeUsage.getUsage(AndroidLibrary.groovy:53)
        at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.from(DefaultMavenPublication.java:132)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
        at com.novoda.gradle.release.ReleasePlugin$_addArtifact_closure3.doCall(ReleasePlugin.groovy:65)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.AbstractPolymorphicDomainObjectContainer.create(AbstractPolymorphicDomainObjectContainer.java:61)
        at org.gradle.api.publish.internal.DefaultPublicationContainer_Decorated.create(Unknown Source)
        at org.gradle.api.publish.internal.DefaultPublicationContainer_Decorated$create.call(Unknown Source)
        at com.novoda.gradle.release.ReleasePlugin.addArtifact(ReleasePlugin.groovy:57)
        at com.novoda.gradle.release.ReleasePlugin$_attachArtifacts_closure2.doCall(ReleasePlugin.groovy:47)
        at com.novoda.gradle.release.ReleasePlugin.attachArtifacts(ReleasePlugin.groovy:45)
        at com.novoda.gradle.release.ReleasePlugin$_apply_closure1.doCall(ReleasePlugin.groovy:15)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
```

Looks like `FOR_RUNTIME` was removed in favour of `JAVA_RUNTIME` in [this commit](https://github.com/gradle/gradle/pull/2450/commits/8b1320fe6dccaa7cf13d25b0ca0797d5b4dd3917) from this PR: https://github.com/gradle/gradle/pull/2450

**Comment by lbx2015** [comment]
I got the same issue when change gradle-4.1-all.zip to gradle-4.2.1-all.zip. How can I solve the Error: No such property: FOR_RUNTIMe for class: org.gradle.api.attributes.usage issue.

**Comment by NoNews** [comment]
Also faced with that

**Comment by StefMa** [comment]
Of course. All people with 4.2 faced it... Make no sense to repeat that
hundred times. A simple reaction would be enough...

On Oct 23, 2017 6:48 PM, "Alex Bykov" <notifications@github.com> wrote:

Also faced with that

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/novoda/bintray-release/issues/138#issuecomment-338722849>,
or mute the thread

**Comment by ronocod** [comment]
Nice! Yeah... I totally tried that 😅 Thanks!
