### ISSUE TITLE
Build bintray-release with Gradle 2.4 fails

### ISSUE THREAD

**Issue by friedger** [novoda/bintray-release#58]
When using gradle 2.4 (in gradle-wrapper.properties) then `gradlew assemble` fails with the following message:

* What went wrong:
java.lang.NullPointerException (no error message)

* Exception is:
java.lang.NullPointerException
        at org.gradle.api.internal.tasks.DefaultTaskDependency.add(DefaultTaskDependency.java:109)
        at org.gradle.api.internal.AbstractTask$11.run(AbstractTask.java:327)
        at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:37)
        at org.gradle.api.internal.AbstractTask.dependsOn(AbstractTask.java:325)
        at com.jfrog.bintray.gradle.BintrayPlugin$_apply_closure2_closure5.doCall(BintrayPlugin.groovy:96)
        at com.jfrog.bintray.gradle.BintrayPlugin$_apply_closure2.doCall(BintrayPlugin.groovy:88)
        at BuildAdapter1_groovyProxy.projectsEvaluated(Unknown Source)

**Comment by friedger** [comment]
When upgrading to gradle 2.4 we need also bintray plugin version 1.2: https://github.com/bintray/gradle-bintray-plugin/commit/5a3d828da0c7176bf25a543b20563d6e7b29c604

**Comment by devisnik** [comment]
Seems like that could be the cause for the crash. :+1:

**Comment by blundell** [comment]
Fixed since we now target gradle 2.8 

https://github.com/novoda/bintray-release/blob/master/gradle/wrapper/gradle-wrapper.properties#L6
