### ISSUE TITLE
java.net.SocketException: Connection reset by peer: socket write error

### ISSUE THREAD

**Issue by yilylong** [novoda/bintray-release#89]
I got an error lik below:
Caused by: java.net.SocketException: Connection reset by peer: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:377)
        at sun.security.ssl.OutputRecord.write(OutputRecord.java:363)

my gradle version 2.10

**Comment by yilylong** [comment]
it seems like https://bintray.com/bintray/jcenter can not connected . i am in china
